title:
  ru: Свято-Владимирский Храм-Памятник
  en: St. Vladimir Memorial Church

keywords:
  ru: "русская православная церковь"
  en: "russian orthodox church nj"

description:
  ru: "Русский православный храм-памятник в г. Джексон, Нью-Джерси"
  en: "Russian orthodox memorial church in Jackson, NJ"

cry_header:
  ru: "Внимание"
  en: "Attention"

cry:
  ru: "Изменения в расписании: служба св Иоанну Шинхайскому переносится на пятницу (3 июля 17:30 всенощная) и субботу (8:30 литкргия). В среду и четверг (1-2 июля) служб не будет."
  en: "Schedule changes: service to St John of Shanghai is moved to Fri (July 3rd 5:30pm vespers) and Sat (July 4th 8:30 liturgy). No services this Wednesday, nor Thursday."

facebook: https://facebook.com/stvladimirsnj
email: info@stvladnj.org
phone:  +1 732 928 1248
instagram: https://www.instagram.com/stvladimirsnj
telegram: https://t.me/stvladnj

google_api_key: AIzaSyDrfmgFWRh8FdeKvsXHOtFapspnxlDk0Hc

google_analytics: "XX-XXXXXXX-XX"

markdown:
  kramdown

collections:
- sections

exclude:
- online-candle-box
- svelte-components
- node_modules
- package.json
- package-lock.json
# - _sections/02a-candles.md
# - _sections/02a-candles-ru.md
