title:
  ru: Свято-Владимирский Храм-Памятник
  en: St. Vladimir Memorial Church

keywords:
  ru: "русская православная церковь"
  en: "russian orthodox church nj"

description:
  ru: "Русский православный храм-памятник в г. Джексон, Нью-Джерси"
  en: "Russian orthodox memorial church in Jackson, NJ"

cry_header:
  ru: "Внимание"
  en: "Attention"

# cry:
#   ru: "В четверг вечером (3 окт) и пятницу утром (4 окт) служб не будет"
#   en: "There will be no services on the evening of Thursday, October 3rd, and morning of Friday, October 4th"

facebook: https://facebook.com/stvladimirsnj
email: info@stvladnj.org
phone:  +1 732 928 1248
instagram: https://www.instagram.com/stvladimirsnj
telegram: https://t.me/stvladnj

google_api_key: AIzaSyDrfmgFWRh8FdeKvsXHOtFapspnxlDk0Hc

google_analytics: "XX-XXXXXXX-XX"

markdown:
  kramdown

collections:
- sections

exclude:
- online-candle-box
- svelte-components
- node_modules
- package.json
- package-lock.json
# - _sections/02a-candles.md
# - _sections/02a-candles-ru.md
