title:
  ru: Свято-Владимирский Храм-Памятник
  en: St. Vladimir Memorial Church

keywords:
  ru: "русская православная церковь"
  en: "russian orthodox church nj"

description:
  ru: "Русский православный храм-памятник в г. Джексон, Нью-Джерси"
  en: "Russian orthodox memorial church in Jackson, NJ"

facebook: https://facebook.com/stvladimirsnj
email: info@stvladnj.org
phone:  +1 732 928 1248

google_api_key: AIzaSyDrfmgFWRh8FdeKvsXHOtFapspnxlDk0Hc

google_analytics: "XX-XXXXXXX-XX"

markdown:
  kramdown

collections:
- sections
