title:
  ru: Свято-Владимирский Храм-Памятник
  en: St. Vladimir Memorial Church

keywords:
  ru: "русская православная церковь"
  en: "russian orthodox church nj"

description:
  ru: "Русский православный храм-памятник в г. Джексон, Нью-Джерси"
  en: "Russian orthodox memorial church in Jackson, NJ"

cry_header:
  ru: "Внимание"
  en: "Attention"

cry:
  ru: "Вечная память новопреставленному Александру Ольховскому. В пятницу 20 декабря в 19:00 - панихида у гроба. В субботу 21 декабря в 7:45 утра - часы и божественная литургия. В 10:30 - отпевание и поминальная трапеза в церковном зале. Все службы возглавит высокопреосвященнейший митрополит Николай."
  en: "Memory eternal to newly reposed Alexander Olhovsky. Panikhida will be served Friday Dec 20 at 7pm. On Sat Dec 21 at 7:45am we will have Hours followed by Divine Liturgy. Funeral at 10:30am and memorial trapeza in the Refectory Hall."

facebook: https://facebook.com/stvladimirsnj
email: info@stvladnj.org
phone:  +1 732 928 1248

google_api_key: AIzaSyDrfmgFWRh8FdeKvsXHOtFapspnxlDk0Hc

google_analytics: "XX-XXXXXXX-XX"

markdown:
  kramdown

collections:
- sections

exclude:
- online-candle-box
- svelte-components
- node_modules
- package.json
- package-lock.json
# - _sections/02a-candles.md
# - _sections/02a-candles-ru.md
